# Generated by Django 5.2.7 on 2025-11-08 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_whishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('product_title', models.CharField(max_length=200)),
                ('product_quantity', models.PositiveIntegerField()),
                ('product_price', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('sgst', models.FloatField(default=0)),
                ('cgst', models.FloatField(default=0)),
                ('shipping_charge', models.FloatField(default=40)),
                ('total_amount', models.FloatField()),
                ('delivery_name', models.CharField(max_length=200)),
                ('delivery_mobile', models.CharField(max_length=10)),
                ('delivery_locality', models.CharField(max_length=200)),
                ('delivery_city', models.CharField(max_length=50)),
                ('delivery_state', models.CharField(max_length=50)),
                ('delivery_zipcode', models.CharField(max_length=10)),
                ('payment_method', models.CharField(default='Online Payment', max_length=50)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_generated', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.orderplaced')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
    ]
